/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jEmzAXvP4RW
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"

export function Component() {
  return (
    (<main
      className="container mx-auto p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 space-y-4 sm:space-y-6 md:space-y-8 lg:space-y-10 xl:space-y-12 bg-[#ffffff] dark:bg-[#000000]">
      <section className="text-center">
        <h1
          className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl xl:text-6xl font-bold tracking-tighter dark:text-white">
          MP3 Downloader
        </h1>
        <p
          className="mx-auto text-sm sm:text-base md:text-lg lg:text-xl xl:text-2xl max-w-[700px] text-gray-500 leading-relaxed dark:text-gray-400">
          Input URLs from YouTube or SoundCloud to download your favorite audio files.
        </p>
      </section>
      <section>
        <div
          className="grid w-full max-w-md sm:max-w-lg md:max-w-xl lg:max-w-2xl xl:max-w-3xl items-center gap-1.5 mx-auto">
          <Label className="dark:text-gray-50" htmlFor="url">
            URL
          </Label>
          <Input className="dark:bg-gray-800 dark:text-gray-50" id="url" type="text" />
        </div>
        <div className="flex justify-center mt-4">
          <Button className="dark:text-gray-50 dark:border-gray-400" variant="outline">
            Search
          </Button>
        </div>
      </section>
      <section>
        <Card
          className="max-w-xs sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl 2xl:max-w-2xl mx-auto dark:bg-gray-800">
          <CardHeader className="dark:text-gray-50">
            <div className="flex items-center gap-2">
              <Badge>Preview</Badge>
              <h2>Audio File Name</h2>
            </div>
          </CardHeader>
          <CardContent className="flex flex-col items-center gap-4">
            <div className="rounded-xl overflow-hidden">
              <audio className="w-full" controls>
                <source src="/audio/placeholder.mp3" type="audio/mpeg" />
              </audio>
            </div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              download
              href="#">
              Download
            </Link>
          </CardContent>
        </Card>
      </section>
    </main>)
  );
}
