/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ti2Qp6Mra7R
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"

export function HomePage() {
  return (
    (<main
      className="container mx-auto p-6 space-y-6 bg-[#ffffff] dark:bg-[#000000]">
      <section className="text-center">
        <h1
          className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl dark:text-white">MP3 Downloader</h1>
        <p
          className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
          Input URLs from YouTube or SoundCloud to download your favorite audio files.
        </p>
      </section>
      <section>
        <div className="grid w-full max-w-sm items-center gap-1.5 mx-auto">
          <Label className="dark:text-gray-50" htmlFor="url">
            URL
          </Label>
          <Input className="dark:bg-gray-800 dark:text-gray-50" id="url" type="text" />
        </div>
        <div className="flex justify-center mt-4">
          <Button className="dark:text-gray-50 dark:border-gray-400" variant="outline">
            Search
          </Button>
        </div>
      </section>
      <section>
        <Card className="max-w-[600px] mx-auto dark:bg-gray-800">
          <CardHeader className="dark:text-gray-50">
            <div className="flex items-center gap-2">
              <Badge>Preview</Badge>
              <h2>Audio File Name</h2>
            </div>
          </CardHeader>
          <CardContent className="flex flex-col items-center gap-4">
            <div className="rounded-xl overflow-hidden">
              <audio className="w-full" controls>
                <source src="/audio/placeholder.mp3" type="audio/mpeg" />
              </audio>
            </div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              download
              href="#">
              Download
            </Link>
          </CardContent>
        </Card>
      </section>
    </main>)
  );
}
